name: flag Kernel
kernel_su:
  enabled: true
  hooks_patch: false
  add_kprobes: false

kernel_su_flags:
  - CONFIG_KSU=y
  - CONFIG_KSU_DEBUG=y
  - CONFIG_KSU_SUSFS=y
  - CONFIG_KSU_SUSFS_SUS_PATH=y
  - CONFIG_KSU_SUSFS_HAS_MAGIC_MOUNT=y
  - CONFIG_KSU_SUSFS_SUS_MOUNT=y
  - CONFIG_KSU_SUSFS_AUTO_ADD_SUS_KSU_DEFAULT_MOUNT=y
  - CONFIG_KSU_SUSFS_AUTO_ADD_SUS_BIND_MOUNT=y
  - CONFIG_KSU_SUSFS_SUS_KSTAT=y
  - CONFIG_KSU_SUSFS_SUS_OVERLAYFS=y
  - CONFIG_KSU_SUSFS_TRY_UMOUNT=y
  - CONFIG_KSU_SUSFS_AUTO_ADD_TRY_UMOUNT_FOR_BIND_MOUNT=y
  - CONFIG_KSU_SUSFS_SPOOF_UNAME=y
  - CONFIG_KSU_SUSFS_ENABLE_LOG=y
  - CONFIG_KSU_SUSFS_HIDE_KSU_SUSFS_SYMBOLS=y
  - CONFIG_KSU_SUSFS_SPOOF_PROC_CMDLINE=y
  - CONFIG_KSU_SUSFS_OPEN_REDIRECT=y
  - CONFIG_KSU_SUSFS_SUS_SU=y
  - CONFIG_WITH_KPROBES=n
  - CONFIG_KPM=y
  - CONFIG_KALLSYMS=y
  - CONFIG_KALLSYMS_ALL=y

overlayfs:
  enabled: true

apatch:
  enabled: false
  fix_openela: false

disable:
  lto: false
  cc_werror: false

old_android:
  enabled: true

fix_wifi_speed: false